apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: composable-manager-role
  labels:
    app.kubernetes.io/name: composable-operator 
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'