apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: composable-leader-election-role
  namespace: composable-operator
  labels:
    app.kubernetes.io/name: composable-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create