apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: composable-leader-election-rolebinding
  namespace: composable-operator
  labels:
    app.kubernetes.io/name: composable-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: composable-leader-election-role
subjects:
- kind: ServiceAccount
  name: composable-operator
  namespace: composable-operator