apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: composable-proxy-rolebinding
  labels:
    app.kubernetes.io/name: composable-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: composable-proxy-role
subjects:
- kind: ServiceAccount
  name: composable-operator
  namespace: composable-operator