apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: composable-selfsigned-issuer
  namespace: composable-operator
  labels:
    app.kubernetes.io/name: composable-operator
spec:
  selfSigned: {}