apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: composable-serving-cert
  namespace: composable-operator
  labels:
    app.kubernetes.io/name: composable-operator
spec:
  commonName: composable-webhook-service.composable-operator.svc
  dnsNames:
  - composable-webhook-service.composable-operator.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: composable-selfsigned-issuer
  secretName: webhook-server-cert