apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    certmanager.k8s.io/inject-ca-from: composable-operator/composable-serving-cert
  creationTimestamp: null
  name: composable-validating-webhook-configuration
  labels:
    app.kubernetes.io/name: composable-operator
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: composable-webhook-service
      namespace: composable-operator
      path: /validate-ibmcloud-ibm-com-v1alpha1-composable
  failurePolicy: Fail
  name: vcomposable.kb.io
  rules:
  - apiGroups:
    - ibmcloud.ibm.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - composables
