apiVersion: v1
kind: Service
metadata:
  name: composable-webhook-service
  namespace: composable-operator
  labels:
    app.kubernetes.io/name: composable-operator
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    control-plane: controller-manager