apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: composable-manager-role
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: composable
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"