apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  name: composable-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: composable-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: composable-operator
    spec:
      containers:
      - args:
        - "-logtostderr=true"
        - "-v=5"
        command:
        - ./manager
        image: registry.ng.bluemix.net/seed/composable-controller:v0.1.0
        imagePullPolicy: Always
        name: composable
      imagePullSecrets:
      - name: ibmcloud-service-operator-pullsecret
      serviceAccountName: composable-service-account